spring:
  application:
    name: springcloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/funtl/spring-cloud-netflix-itoken/tree/master/itoken-config-respo/
          search-paths: respo
          username:
          password:

#一般默认8888
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
