spring:
  application:
    name: springcloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/outman123/springcloud.git
          search-paths: config/respo
          username:
          password:
  zipkin:
    base-url: http://localhost:8120

#一般默认8888
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/