spring:
  application:
    name: springcloud-zuul
  zipkin:
    base-url: http://localhost:8120

server:
  port: 8106

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/


zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: springcloud-web-admin-feign
    api-b:
      path: /api/b/**
      serviceId: springcloud-web-admin-ribbon