spring:
  application:
    name: springcloud-service-admin
  zipkin:
    base-url: http://localhost:8120
server:
  port: 8101

#eureka 基本信息配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
