spring:
  application:
    name: springcloud-web-admin-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html

server:
  port: 8110
#eureka 基本信息配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/